import type { estadosCaso } from './expediente.catalogs';

export type EstadoCaso = (typeof estadosCaso)[number];

export type Familiar = { nombre: string; edad: number | ''; parentesco: string; ocupacion: string; escolaridad: string; enfermedad: string };
export type RedApoyo = { tipoApoyo: string; nombreCompleto: string; tipoRelacion: string; telefono: string; direccionCompleta: string };

export type ExpedienteForm = {
  folioBanavim?: string;
  numeroExpediente?: string;
  comoSeEntero: string;
  fechaAtencion: string;
  indigena: 'Sí' | 'No';
  migrante: 'Sí' | 'No';
  reingreso: 'Sí' | 'No';
  violenciaUltimos12Meses: 'Sí' | 'No';
  apellidoPaterno: string;
  apellidoMaterno: string;
  nombres: string;
  estadoCivil: string;
  sexo: string;
  edad: number | '';
  fechaNacimiento: string;
  municipioNacimiento: string;
  estadoNacimiento: string;
  paisNacimiento: string;
  nacionalidad: string;
  religion: string;
  curp: string;
  telefono: string;
  grupoEtnico: 'Sí' | 'No' | 'Desconoce';
  hablaLenguaIndigena: 'Sí' | 'No';
  lenguaIndigenaCual?: string;
  hablaLenguaExtranjera: 'Sí' | 'No';
  lenguaExtranjeraCual?: string;
  hijas: number | '';
  hijos: number | '';
  calle: string;
  numeroExterior: string;
  numeroInterior: string;
  colonia: string;
  codigoPostal: string;
  municipio: string;
  estado: string;
  pais: string;
  familiares: Familiar[];
  dedicacion: string;
  ingresoMensual: number | '';
  jornadaLaboral: string;
  fuenteIngresos: string;
  jefaFamilia: 'Sí' | 'No';
  escolaridad: string;
  vivienda: string;
  servicioMedico: string;
  embarazo: 'Sí' | 'No' | 'No sabe';
  enfermedad: 'Sí' | 'No';
  enfermedadCual?: string;
  medicamentos: 'Sí' | 'No';
  medicamentosCual?: string;
  drogas: 'Sí' | 'No';
  drogasCual?: string;
  capacidades: Record<string, string>;
  redesApoyo: RedApoyo[];
  mediaFiliacion: string;
  conoceGenerador: 'Sí' | 'No';
  generadorNombre?: string;
  generadorRelacion?: string;
  generadorRiesgo: 'Leve' | 'Moderado' | 'Grave';
  actosCometidos: string[];
  caracteristicasRiesgo: string[];
  notasGenerador?: string;
  fechaAgresion: string;
  horaAgresion: string;
  lugarAgresion: string;
  municipioAgresion: string;
  estadoAgresion: string;
  vecesAgresion: number | '';
  diaFestivo: 'Sí' | 'No';
  diaFestivoCual?: string;
  autoridadConoce: 'Sí' | 'No';
  autoridadCual?: string;
  denuncio: string;
  tiposViolencia: string[];
  modalidadesViolencia: string[];
  efectosFisicos: string[];
  efectosPsicologicos: string[];
  efectosEconomicos: string[];
  efectosSexuales: string[];
  agenteLesion: string;
  areaAnatomica: string;
  motivoAtencion: string;
  recibioInformacion: 'Sí' | 'No';
  materiaInformacion?: string;
  solicitudes: string[];
  narracion: string;
  personaAtiende: string;
  observacionesAutorizadas: string;
  firmaFisica: boolean;
  confirmacionRevision: boolean;
};

export type ExpedienteListItem = {
  id: string;
  numeroExpediente: string;
  folioBanavim?: string;
  nombreCompleto: string;
  curp?: string;
  telefono?: string;
  ultimaAtencion: string;
  estado: EstadoCaso;
};

export type Expediente = ExpedienteListItem & { detalle: ExpedienteForm; historial: Array<{ fecha: string; evento: string; responsable: string }> };

export type ExpedienteFilters = { busqueda?: string; nombre?: string; curp?: string; folioBanavim?: string; numeroExpediente?: string; fechaAtencion?: string; estado?: string };
