import { useState } from 'react';
import { Button, DataTable, EmptyState, ErrorState, LoadingState } from '../../shared/components/Ui';
import { SelectField, TextField } from '../../shared/components/FormControls';
import { env } from '../../shared/config/env';
import { modalidadesViolencia, tiposViolencia } from '../expedientes/expediente.catalogs';
import { getReporteAtenciones, type ReporteFilters, type ReporteRow } from './reporte.service';

export function ReportesPage() {
  const [filters, setFilters] = useState<ReporteFilters>({}); const [rows, setRows] = useState<ReporteRow[]>([]); const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  async function submit(event: React.FormEvent) { event.preventDefault(); try { setStatus('loading'); setRows(await getReporteAtenciones(filters)); setStatus('success'); } catch { setStatus('error'); } }
  return <section className="page"><div className="page-header"><h1>Reportes</h1><p>Resultados agregados para consulta institucional.</p></div>{env.useMocks ? <p className="mock-note">La exportación PDF/Excel estará habilitada al conectar el servicio correspondiente. No se generarán archivos falsos.</p> : null}<form className="filters" onSubmit={submit}><TextField label="Fecha inicial" type="date" value={filters.fechaInicial ?? ''} onChange={(e) => setFilters({ ...filters, fechaInicial: e.target.value })} /><TextField label="Fecha final" type="date" value={filters.fechaFinal ?? ''} onChange={(e) => setFilters({ ...filters, fechaFinal: e.target.value })} /><SelectField label="Tipo de violencia" value={filters.tipoViolencia ?? ''} onChange={(e) => setFilters({ ...filters, tipoViolencia: e.target.value })}><option value="">Todos</option>{tiposViolencia.map((item) => <option key={item}>{item}</option>)}</SelectField><SelectField label="Modalidad" value={filters.modalidad ?? ''} onChange={(e) => setFilters({ ...filters, modalidad: e.target.value })}><option value="">Todas</option>{modalidadesViolencia.map((item) => <option key={item}>{item}</option>)}</SelectField><TextField label="Estado de seguimiento" value={filters.estadoSeguimiento ?? ''} onChange={(e) => setFilters({ ...filters, estadoSeguimiento: e.target.value })} /><TextField label="Tipo de atención" value={filters.tipoAtencion ?? ''} onChange={(e) => setFilters({ ...filters, tipoAtencion: e.target.value })} /><Button type="submit">Buscar</Button><Button type="button" className="button-secondary" disabled={env.useMocks}>Exportar PDF</Button><Button type="button" className="button-secondary" disabled={env.useMocks}>Exportar Excel</Button></form>{status === 'loading' ? <LoadingState /> : null}{status === 'error' ? <ErrorState message="No fue posible generar la vista previa del reporte." /> : null}{status === 'success' && !rows.length ? <EmptyState message="No hay datos agregados para los filtros." /> : null}{status === 'success' && rows.length ? <><DataTable caption="Vista previa agregada" rows={rows} getKey={(row) => row.concepto} columns={[{ header: 'Concepto', render: (row) => row.concepto }, { header: 'Total', render: (row) => row.total }, { header: 'Periodo', render: (row) => row.periodo }]} /><p className="total-box">Total agregado: {rows.reduce((sum, row) => sum + row.total, 0)}</p></> : null}</section>;
}
